package com.foxinsurance.training.data;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.simple.JdbcClient;

public class SchemaInitializer {
	private final JdbcClient jdbc;

	public SchemaInitializer(JdbcClient jdbc) {
		this.jdbc = jdbc;
	}

	@PostConstruct
	public void init() {
		jdbc.sql(
				"CREATE TABLE IF NOT EXISTS policies (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_name VARCHAR(100) NOT NULL, product_type VARCHAR(30) NOT NULL, premium DECIMAL(12,2) NOT NULL, status VARCHAR(30) NOT NULL)")
				.update();
		jdbc.sql(
				"CREATE TABLE IF NOT EXISTS policy_audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, policy_id BIGINT, action VARCHAR(100) NOT NULL)")
				.update();
	}
}
